#!/usr/bin/env python3
"""
Public smoke test: Minimal generation/export contract verification
Uses fictitious, safe fixture - no real client data
"""
import json
import tempfile
import subprocess
import sys
from pathlib import Path


def test_generation_contract():
    """Test that the generation pipeline can process a minimal blueprint."""
    # Create a minimal test project
    with tempfile.TemporaryDirectory() as tmpdir:
        project_dir = Path(tmpdir) / "test-smoke"
        project_dir.mkdir()

        # Minimal blueprint with fictitious content
        blueprint = {
            "project_name": "test-smoke",
            "topic": "Public Smoke Test - Fictitious Company",
            "slides": [
                {
                    "id": 1,
                    "slide_id": "slide_01",
                    "title": "Test Slide",
                    "purpose": "Verify generation pipeline works",
                    "layout": "title_content",
                    "layout_tag": "title_content",
                    "content": {
                        "headline": "Test Slide",
                        "body": "This is a fictitious test slide for smoke testing."
                    },
                    "notes": "Generated by public smoke test"
                }
            ]
        }

        (project_dir / "blueprint.json").write_text(json.dumps(blueprint, indent=2))

        # Run authoring phase
        result = subprocess.run(
            [sys.executable, "my-ppt-skill/scripts/build_project.py", str(project_dir), "--phase", "authoring"],
            capture_output=True,
            text=True,
            cwd="."
        )

        # Check that authoring phase completes
        assert result.returncode == 0, f"Authoring failed: {result.stderr}"

        # Check SVG was generated
        svg_file = project_dir / "svg_output" / "slide_01.svg"
        assert svg_file.exists(), f"SVG not generated: {svg_file}"

        svg_content = svg_file.read_text()
        assert "<svg" in svg_content
        assert "Test Slide" in svg_content

        print("Generation contract test PASSED")


def test_export_contract():
    """Test that export pipeline runs and produces PPTX."""
    with tempfile.TemporaryDirectory() as tmpdir:
        project_dir = Path(tmpdir) / "test-smoke-export"
        project_dir.mkdir()

        # Minimal blueprint
        blueprint = {
            "project_name": "test-smoke-export",
            "topic": "Export Test",
            "slides": [
                {
                    "id": 1,
                    "slide_id": "slide_01",
                    "title": "Export Test",
                    "purpose": "Verify export works",
                    "layout": "title_content",
                    "layout_tag": "title_content",
                    "content": {
                        "headline": "Export Test",
                        "body": "Testing PPTX export."
                    },
                    "notes": "Export test"
                }
            ]
        }

        (project_dir / "blueprint.json").write_text(json.dumps(blueprint, indent=2))

        # Run authoring first to generate SVG
        result = subprocess.run(
            [sys.executable, "my-ppt-skill/scripts/build_project.py", str(project_dir), "--phase", "authoring"],
            capture_output=True,
            text=True,
            cwd="."
        )
        assert result.returncode == 0, f"Authoring failed: {result.stderr}"

        # Then finalize with skip-qa to verify export pipeline works
        result = subprocess.run(
            [sys.executable, "my-ppt-skill/scripts/build_project.py", str(project_dir), "--phase", "finalize", "--skip-render", "--skip-qa"],
            capture_output=True,
            text=True,
            cwd="."
        )

        assert result.returncode == 0, f"Export failed: {result.stderr}"

        # Check PPTX was generated
        pptx_files = list(project_dir.glob("exports/*.pptx"))
        assert len(pptx_files) > 0, "No PPTX generated"

        print("Export contract test PASSED")


if __name__ == "__main__":
    test_generation_contract()
    test_export_contract()